name: Email Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Display Email 23ds2000055@ds.study.iitm.ac.in
        run: echo "Hello, 23ds2000055@ds.study.iitm.ac.in"
